name: setup

on:
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change files
      run: |
        PACKAGE_NAME=$(echo "${{ github.event.repository.name }}" | sed -r 's|-|_|g')

        sed -i -E 's|name=\".*?\"|name="'"$PACKAGE_NAME"'"|g' setup.py
        sed -i -E 's|author=\".*?\"|author="${{ github.event.repository.owner.login }}"|g' setup.py
        sed -i -E 's|description=\".*?\"|description="${{ github.event.repository.description }}"|g' setup.py
        sed -i -E 's|url=\".*?\"|url="${{ github.event.repository.html_url }}"|g' setup.py

        sed -i -E 's|project = ".*?"|project = "'"$PACKAGE_NAME"'"|g' docs/conf.py
        sed -i -E 's|copyright = ".*?"|copyright = "${{ github.event.repository.license.name }}"|g' docs/conf.py
        sed -i -E 's|author = ".*?"|author = "${{ github.event.repository.owner.login }}"|g' docs/conf.py

        sed -i -E "s|automodule\:\: .+?$|automodule\:\: ""$PACKAGE_NAME""|gm" docs/index.rst
        sed -i -E "s|Welcome to .+?'s|Welcome to ""$PACKAGE_NAME""'s|g" docs/index.rst

        mv python_package_automation/ "$PACKAGE_NAME"/

        rm -f .github/workflows/setup.yml

    - name: Push changes to github
      run: |
        git add -A
        git config --global user.email "none@none.com"
        git config --global user.name "setup bot"
        git commit -m 'Setting up repo'
        git push origin ${{ github.ref }}
