name: sphinxbuild

on:
  workflow_dispatch:
  release:
    types:
      - published
    
jobs:

  update-gh-pages:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          git checkout -b gh-pages
          THEME=$(grep -oP '(?<=html_theme = ").+?(?=")' docs/conf.py)
          python3 -m pip install --upgrade pip
          pip install sphinx $THEME sphinxcontrib-programoutput .
          python3 setup.py install
      - name: Change conf.py version
        run: |
          sed -i -E 's|release = ".*?"|release = "${{ github.event.release.tag_name }}"|g' docs/conf.py
      - name: Build using sphinx
        run: |
          sphinx-build -M html docs/ build/
          find . -mindepth 1 ! -regex '^./build\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete
          find build/* -maxdepth 1 -mindepth 1 -not -name build -exec mv '{}' . \;
          rm -rf build/
          touch .nojekyll
          git add -A
          git config --global user.email "none@none.com"
          git config --global user.name "release bot"
          git commit -m 'Updating page version (triggered by new release)'
          git push origin gh-pages --force